# Generated by Django 2.1.15 on 2020-04-01 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reiview',
            new_name='Review',
        ),
    ]
